SELECT T1.TABLE_NAME,        
        T1.COMMENTS TABLE_COMMENTS,
        T1.TABLE_TYPE,
        T1.COLUMN_NAME,
        T1.DATA_TYPE,
        T1.DATA_LENGTH,
        T1.DATA_PRECISION,
        T1.NULLABLE,
        T1.COLUMN_COMMENTS COLUMN_COMMENTS,
        T2.POSITION PK_INDEX,
        T3.REFERENCE_TABLE,
        T3.REFERENCE_COLUMN
FROM 
(

(
SELECT C_TABLE.TABLE_NAME,
        C_TABLE.OWNER,
        C_TABLE_COMMENTS.COMMENTS,
        C_TABLE_COMMENTS.TABLE_TYPE,
        C_TABLE_COLUMN.COLUMN_NAME,
        C_TABLE_COLUMN.DATA_TYPE,
        C_TABLE_COLUMN.DATA_LENGTH,
        C_TABLE_COLUMN.DATA_PRECISION,
        C_TABLE_COLUMN.NULLABLE,		        
        C_TABLE_COLUMN_COMMENTS.COMMENTS COLUMN_COMMENTS        
    FROM 
        ALL_TABLES C_TABLE,
        ALL_TAB_COMMENTS C_TABLE_COMMENTS,
        ALL_TAB_COLS C_TABLE_COLUMN,
        ALL_COL_COMMENTS C_TABLE_COLUMN_COMMENTS
        
    WHERE 
        C_TABLE_COMMENTS.TABLE_NAME = C_TABLE.TABLE_NAME
        AND C_TABLE_COMMENTS.OWNER = C_TABLE.OWNER
        AND C_TABLE_COLUMN.TABLE_NAME = C_TABLE.TABLE_NAME
        AND C_TABLE_COLUMN.OWNER = C_TABLE.OWNER
        AND C_TABLE_COLUMN_COMMENTS.OWNER = C_TABLE_COLUMN.OWNER
        AND C_TABLE_COLUMN_COMMENTS.TABLE_NAME = C_TABLE_COLUMN.TABLE_NAME
        AND C_TABLE_COLUMN_COMMENTS.COLUMN_NAME = C_TABLE_COLUMN.COLUMN_NAME
        AND C_TABLE.OWNER = @schemaName
        AND @tableName1 
)
UNION
(
SELECT C_TABLE.VIEW_NAME TABLE_NAME,
        C_TABLE.OWNER,
        C_TABLE_COMMENTS.COMMENTS,
        C_TABLE_COMMENTS.TABLE_TYPE,
        C_TABLE_COLUMN.COLUMN_NAME,
        C_TABLE_COLUMN.DATA_TYPE,
        C_TABLE_COLUMN.DATA_LENGTH,
        C_TABLE_COLUMN.DATA_PRECISION,
        C_TABLE_COLUMN.NULLABLE,		        
        C_TABLE_COLUMN_COMMENTS.COMMENTS COLUMN_COMMENTS        
    FROM 
        ALL_VIEWS C_TABLE,
        ALL_TAB_COMMENTS C_TABLE_COMMENTS,
        ALL_TAB_COLS C_TABLE_COLUMN,
        ALL_COL_COMMENTS C_TABLE_COLUMN_COMMENTS
        
    WHERE 
        C_TABLE_COMMENTS.TABLE_NAME = C_TABLE.VIEW_NAME
        AND C_TABLE_COMMENTS.OWNER = C_TABLE.OWNER
        AND C_TABLE_COLUMN.TABLE_NAME = C_TABLE.VIEW_NAME
        AND C_TABLE_COLUMN.OWNER = C_TABLE.OWNER
        AND C_TABLE_COLUMN_COMMENTS.OWNER = C_TABLE_COLUMN.OWNER
        AND C_TABLE_COLUMN_COMMENTS.TABLE_NAME = C_TABLE_COLUMN.TABLE_NAME
        AND C_TABLE_COLUMN_COMMENTS.COLUMN_NAME = C_TABLE_COLUMN.COLUMN_NAME
        AND C_TABLE.OWNER = @schemaName
        AND @viewName1
)
        
) T1,
(        
SELECT C.TABLE_NAME, C.OWNER, C.CONSTRAINT_NAME,C.COLUMN_NAME,C.POSITION
      FROM ALL_CONS_COLUMNS C
      WHERE OWNER = @schemaName
      AND @tableName2 
      AND CONSTRAINT_NAME = ( SELECT CONSTRAINT_NAME
      FROM ALL_CONSTRAINTS
      WHERE TABLE_NAME = C.TABLE_NAME
      AND CONSTRAINT_TYPE = 'P'
      AND OWNER = C.OWNER
      )  
) T2,
(
SELECT UNIQUE A.CONSTRAINT_NAME,
      A.TABLE_NAME,
      A.OWNER,
      C.COLUMN_NAME COLUMN_NAME ,
      B.TABLE_NAME REFERENCE_TABLE,
      B.COLUMN_NAME REFERENCE_COLUMN,
      A.R_CONSTRAINT_NAME ,
      C.POSITION
      FROM ALL_CONSTRAINTS A, ALL_CONS_COLUMNS B, ALL_CONS_COLUMNS C
      WHERE A.R_CONSTRAINT_NAME=B.CONSTRAINT_NAME      
      AND A.CONSTRAINT_NAME=C.CONSTRAINT_NAME
      AND A.OWNER=C.OWNER
      AND A.OWNER = B.OWNER       
      AND A.TABLE_NAME=C.TABLE_NAME
      AND B.POSITION=C.POSITION
      AND A.OWNER=@schemaName
      AND @tableName3
      ORDER BY A.CONSTRAINT_NAME, C.POSITION
) T3
WHERE 
T1.TABLE_NAME = T2.TABLE_NAME(+) 
AND T1.OWNER = T2.OWNER(+)
AND T1.COLUMN_NAME = T2.COLUMN_NAME(+)
AND T1.TABLE_NAME = T3.TABLE_NAME(+) 
AND T1.OWNER = T3.OWNER(+)
AND T1.COLUMN_NAME = T3.COLUMN_NAME(+)
ORDER BY 
	T1.TABLE_NAME,PK_INDEX,T1.COLUMN_NAME
