CREATE TABLE accounts (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    balance DEC(15, 2) NOT NULL,
    PRIMARY KEY(id)
);

INSERT INTO accounts(name, balance) VALUES('Raju', 10000);
INSERT INTO accounts(name, balance) VALUES('Nikhil', 10000);

CREATE OR REPLACE PROCEDURE transfer(
   sender INT,
   receiver INT,
   amount dec
)
LANGUAGE plpgsql
AS $$
BEGIN
    -- Subtracting the amount from the sender's account
    UPDATE accounts
    SET balance = balance - amount
    WHERE id = sendeAr;

    -- Adding the amount to the receiver's account
    UPDATE accounts
    SET balance = balance + amount
    WHERE id = receiver;

    COMMIT;
END; $$;



CREATE OR REPLACE PROCEDURE create_cache(
  IN code TEXT,
  IN cache TEXT
)
LANGUAGE plpgsql
AS $$
BEGIN
  INSERT INTO cache (code, cache)
  VALUES (code, cache);
END;
$$;

CREATE FUNCTION add(a integer, b integer) RETURNS integer
    LANGUAGE SQL
    IMMUTABLE
    RETURNS NULL ON NULL INPUT
    RETURN a + b;