CREATE TABLE accounts (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    balance DEC(15, 2) NOT NULL,
    PRIMARY KEY(id)
);

INSERT INTO accounts(name, balance) VALUES('Raju', 10000);
INSERT INTO accounts(name, balance) VALUES('Nikhil', 10000);

CREATE OR REPLACE PROCEDURE transfer(
   sender INT,
   receiver INT,
   amount DECIMAL(15, 2)
)
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE accounts
    SET balance = balance - amount
    WHERE id = sender;

    UPDATE accounts
    SET balance = balance + amount
    WHERE id = receiver;
END;
$$;



CREATE OR REPLACE PROCEDURE create_cache(
  IN code TEXT,
  IN cache TEXT
)
LANGUAGE plpgsql
AS $$
BEGIN
  INSERT INTO cache (code, cache)
  VALUES (code, cache);
END;
$$;

CREATE FUNCTION add(a integer, b integer) RETURNS integer
    LANGUAGE SQL
    IMMUTABLE
    RETURNS NULL ON NULL INPUT
    RETURN a + b;

-- IN + single OUT (procedure): output length of the message.
CREATE OR REPLACE PROCEDURE sp_echo_len(IN p_msg text, OUT p_len int)
LANGUAGE plpgsql
AS $$
BEGIN
  p_len := length(p_msg);
END;
$$;

-- IN + multiple OUT: quotient and remainder when dividing by 3.
CREATE OR REPLACE PROCEDURE sp_divmod(IN p_n int, OUT p_q int, OUT p_r int)
LANGUAGE plpgsql
AS $$
BEGIN
  p_q := p_n / 3;
  p_r := p_n % 3;
END;
$$;

-- Two IN + two OUT (no INOUT): sum and product — exercises multiple IN with multiple OUT.
CREATE OR REPLACE PROCEDURE sp_sum_product(
  IN p_a int,
  IN p_b int,
  OUT p_sum int,
  OUT p_product int
)
LANGUAGE plpgsql
AS $$
BEGIN
  p_sum := p_a + p_b;
  p_product := p_a * p_b;
END;
$$;

-- INOUT only: doubles the passed value in place.
CREATE OR REPLACE PROCEDURE sp_double_inout(INOUT p_value int)
LANGUAGE plpgsql
AS $$
BEGIN
  p_value := p_value * 2;
END;
$$;

-- OUT only: fixed values (tests OUT without IN).
CREATE OR REPLACE PROCEDURE sp_fixed_pair(OUT p_a int, OUT p_b int)
LANGUAGE plpgsql
AS $$
BEGIN
  p_a := 21;
  p_b := 22;
END;
$$;

-- Pure IN combination (three IN parameters, scalar return).
CREATE OR REPLACE FUNCTION fn_sum_three(a integer, b integer, c integer) RETURNS integer
    LANGUAGE SQL
    IMMUTABLE
    AS $$ SELECT a + b + c $$;

-- Single array-typed IN (JDBC ARRAY / metadata TYPE_NAME often "_int4"); scalar return.
CREATE OR REPLACE FUNCTION fn_array_sum(p_values integer[]) RETURNS integer
    LANGUAGE sql
    IMMUTABLE
    AS $$ SELECT COALESCE((SELECT SUM(x) FROM unnest(p_values) AS u(x)), 0) $$;

-- Second scalar routine with the same JDBC shape as fn_array_sum (one integer[] IN).
-- A true PostgreSQL VARIADIC parameter cannot be invoked as fn(integer[]) from JDBC:
-- the server expects either expanded arguments (1, 2, 3) or SQL
-- fn_name(VARIADIC array_expr), which generated {? = call fn(?)} does not emit.
CREATE OR REPLACE FUNCTION fn_variadic_sum(p_values integer[]) RETURNS integer
    LANGUAGE sql
    IMMUTABLE
    AS $$ SELECT COALESCE((SELECT SUM(x) FROM unnest(p_values) AS u(x)), 0) $$;