# This workflow will build a package then publish to GitHub Maven Access controlled repository

name: Publish to github Maven Repo

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: zulu
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Publish puglin to GitHub Maven Repository
        run: mvn -DskipTests deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
